# fly.toml app configuration file generated for t-mt-api on 2023-06-10T18:56:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "t-mt-api"
primary_region = "waw"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
